# Aktualisierung des Helpers input_number.evcc_garage_vehicle_soc
- alias: Refresh EVCC Garage Vehicle SOC
  id: 4f5bee82d067459ebcaf60976a246468
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sensor.evcc_garage_vehicle_soc
  action:
    - service: input_number.set_value
      target:
        entity_id: input_number.evcc_garage_vehicle_soc
      data:
        value: '{{ states(''sensor.evcc_garage_vehicle_soc'') }}'
